# Generated by Django 6.0.3 on 2026-04-02 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blood_type_needed', models.CharField(max_length=5)),
                ('units_needed', models.PositiveSmallIntegerField(default=1)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('needed_date', models.DateField()),
                ('details', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blood_type_needed', 'status'], name='announcemen_blood_t_345ed8_idx'), models.Index(fields=['needed_date'], name='announcemen_needed__6b5f62_idx'), models.Index(fields=['status', 'needed_date'], name='announcemen_status_d2aaab_idx')],
            },
        ),
    ]
